//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfumeSalone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string Articul { get; set; }
        public string Name { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> MaxDiscount { get; set; }
        public string Developer { get; set; }
        public string Provider { get; set; }
        public string Category { get; set; }
        public Nullable<int> CurrentDiscount { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    }
}
